
name: Flutter publish to firebase (upload artifacts android)
  # deploy_beta_android:
  #   name: Flutter publish to firebase (upload artifacts android)
  #   needs: [build_app]
  #   runs-on: ubuntu-latest
inputs: 
  FIREBASE_ANDROID_APPID:
    required: true
  CREDENTIAL_FILE_CONTENT:
    required: true
  FIREBASE_PROJECT_ID:
    required: true
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v4
    
    - name: set up java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        # cache: 'yarn'          

    - run: npm install -g firebase-tools
    # - uses: w9jds/setup-firebase@main  #Alternative for firebase-action)
    #   with:
    #     tools-version: 13.8.2
    #     firebase_token: ${{ secrets.FIREBASE_TOKEN }}          

    - name: download artifact from github_releases
      uses: actions/download-artifact@master
      with:
        name: APPBUNDLE
        path: build/app/outputs/bundle/release/app-release.aab
    - name: Upload artifact to Firebase App Distribution
      uses: mastersam07/firebase-app-distribution-action@v0.1 # (other alternatives: w9jds/firebase-action@master, wzieba/Firebase-Distribution-Github-Action@v1.0.0)
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        file: app-release.apk        
        # token: ${{secrets.FIREBASE_TOKEN}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: 'testers'
    - name: upload artifact to Firebase App Distribution (2)
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_PROJECT_ID}}
        file: build/app/outputs/bundle/release/app-release.aab
        # token: ${{secrets.FIREBASE_TOKEN}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: 'testers'

    # - name: Deploy to Firebase
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: deploy --only hosting
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}          

          