// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrM5FyrmiTHCHqfQk0L2ZM9tesReEVsPw',
    appId: '1:503506246817:android:543ba4134f37f23e11e4e0',
    messagingSenderId: '503506246817',
    projectId: 'strongline-app1-flutter-4dbd6',
    storageBucket: 'strongline-app1-flutter-4dbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbG5Kq2jlzjkwx7cP7MPUWUxdaLQ5-JTc',
    appId: '1:503506246817:ios:ed8733a4ecda07de11e4e0',
    messagingSenderId: '503506246817',
    projectId: 'strongline-app1-flutter-4dbd6',
    storageBucket: 'strongline-app1-flutter-4dbd6.appspot.com',
    iosBundleId: 'com.example.app1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbG5Kq2jlzjkwx7cP7MPUWUxdaLQ5-JTc',
    appId: '1:503506246817:ios:ed8733a4ecda07de11e4e0',
    messagingSenderId: '503506246817',
    projectId: 'strongline-app1-flutter-4dbd6',
    storageBucket: 'strongline-app1-flutter-4dbd6.appspot.com',
    iosBundleId: 'com.example.app1Flutter',
  );

}