  deploy_beta_ios:
    name: Flutter publish to firebase (upload artifacts iOS)
    needs: [build_app]
    runs-on: ubuntu-latest
    steps:
      - name: set up java
        uses: actions/setup-java@v3    
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          # cache: 'yarn'          
        
      - uses: w9jds/setup-firebase@main # alternative to firebase-action
        with:
          tools-version: 13.9.0
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}             
      - name: download artifact from github_releases
        uses: actions/download-artifact@master
        with:
          name: ios-build
      # - name: Upload IPA
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_IOS_APPID}}
      #     token: ${{secrets.FIREBASE_TOKEN}}
      #     group: testers
      #     file: Runner.ipa   
      - name: Upload IPA
        uses: mastersam07/firebase-app-distribution-action@v0.1 # (other alternatives: w9jds/firebase-action@master, wzieba/Firebase-Distribution-Github-Action@v1.0.0)
        with:
          appId: ${{secrets.FIREBASE_IOS_APPID}}
          file: Runner.ipa        
          # token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: 'testers'
          